# Make the background transparent
background_opacity 0.2
# makes the annoying confirmation screen dissapear
confirm_os_window_close 0
#font(change if you dont use this one)
font_family JetBrainsMono Nerd Font

